// This file is auto-generated by scripts/gen-build-info.mjs
export const buildInfo = {
  buildTimeISO: "2026-01-05T10:09:05.523Z",
  appVersion: "0.0.0",
  commitHash: "ea9b8a3",
  env: "production"
};
