// This file is auto-generated by scripts/gen-build-info.mjs
export const buildInfo = {
  buildTimeISO: "2026-01-04T15:47:29.120Z",
  appVersion: "0.0.0",
  commitHash: "27664d8",
  env: "production"
};
